### ISSUE TITLE
The link provided in the description of the Github does not work.

### ISSUE THREAD

**Issue by joelou1** [cozyGalvinism/TGPToolchain#7]
**Describe the bug**
The link to the latest Mod tool brings to an unverified and hence unaccessable website. 

**To Reproduce**
1. Go to TGPToolchain's Github and go to the bottom of the project's description.
2. Click on the provided link to the lastest version of TGPToolchain
3. See error

**Expected behavior**
Clicking on the link should send you to the proper website contaning the latest download links OR send you to the github's download section.

**Screenshots**
![image](https://github.com/cozyGalvinism/TGPToolchain/assets/1740156/dda41092-08b8-4e0b-91fb-8b329d33d78f)
![image](https://github.com/cozyGalvinism/TGPToolchain/assets/1740156/4e98d5ae-fc7e-474c-bb5a-6ed80d5dc636)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version : Latest

**Additional context**
I am unsure if 1.0.7 is the latest update since there's a link going outside, so I have not downloaded anything yet.

**Comment by cozyGalvinism** [comment]
Yeah no, that CI has been dead for a while, I should update the README at some point.

Latest version currently is [here](https://github.com/cozyGalvinism/TGPToolchain/releases/tag/v1.0.7).

**Comment by cozyGalvinism** [comment]
Fixed in a81ac16
